fix: update view policy inputs to match angular
certua/get-started-open-banking-elements-vue pull request #12
Opened 2023-11-15 09:17 UTC by charleystagg-certua

2023-11-15 12:21 UTC, gregduffield requested changes

2023-11-15 12:21 UTC, gregduffield commented on src/App.vue
can we remove the old view policy link please as we are only showing them view policy 2 (now called view policy)

2023-11-16 13:13 UTC, charleystagg-certua commented
I have removed the commented out menu links - is that what you meant? the only link showing is for the view policy 2. (the comment above doesn't want to load the diff to show me where in  the comment was made in the code :) )

2023-11-23 16:35 UTC, vickieallen-certua approved these changes

2023-11-23 16:35 UTC, merged